In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("nepal_bank_transactions.csv")

In [5]:
for column in df.columns:
    print(column)

transaction_id
date
time
branch_name
district
channel
transaction_type
card_type
account_type
amount_npr
response_code
response_message
transaction_status
customer_age
customer_gender
processing_time_ms

In [6]:
df.head()

,transaction_id,date,time,branch_name,district,channel,transaction_type,card_type,account_type,amount_npr,response_code,response_message,transaction_status,customer_age,customer_gender,processing_time_ms
0,TXN0000001,2024-01-01,00:43:34,New Baneshwor,Kathmandu,ATM,Mini Statement,Credit Card,Current,0.00,0,Approved,Success,26.0,Female,1322
1,TXN0000002,2024-01-01,01:04:46,Dhangadhi Branch,Kailali,Internet Banking,Statement Download,NaN,Savings,0.00,0,Approved,Success,30.0,NaN,711
2,TXN0000003,2024-01-01,06:41:33,Hetauda Branch,Makwanpur,ATM,PIN Change,Debit Card,Savings,0.00,0,Approved,Success,58.0,Female,1633
3,TXN0000004,2024-01-01,07:46:42,Butwal Branch,Rupandehi,Mobile Banking,Fund Transfer,NaN,Savings,97651.24,0,Approved,Success,56.0,Female,816
4,TXN0000005,2024-01-01,08:44:14,Janakpur Branch,Dhanusha,ATM,Mini Statement,Debit Card,Savings,0.00,0,Approved,Success,37.0,Male,1168

In [7]:
df.tail()

,transaction_id,date,time,branch_name,district,channel,transaction_type,card_type,account_type,amount_npr,response_code,response_message,transaction_status,customer_age,customer_gender,processing_time_ms
6055,TXN0005996,2024-12-31,17:47:21,Kathmandu Main,Kathmandu,Mobile Banking,Balance Inquiry,NaN,Savings,0.00,0,Approved,Success,38.0,Female,401
6056,TXN0005997,2024-12-31,18:22:58,Dhangadhi Branch,Kailali,ATM,Cash Withdrawal,Debit Card,Savings,3000.00,0,Approved,Success,18.0,Female,970
6057,TXN0005998,2024-12-31,19:45:09,Birgunj Branch,Parsa,Mobile Banking,Fund Transfer,NaN,Savings,86174.23,0,Approved,Success,33.0,Male,435
6058,TXN0005999,2024-12-31,21:00:21,New Baneshwor,Kathmandu,ATM,Cash Withdrawal,Debit Card,Savings,1000.00,0,Approved,Success,41.0,Male,901
6059,TXN0006000,2024-12-31,22:32:17,Butwal Branch,Rupandehi,Mobile Banking,QR Payment,NaN,Savings,4014.87,55,Incorrect PIN,Reversed,18.0,Female,651

In [8]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 6060 entries, 0 to 6059
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      6060 non-null   str
 1   date                6060 non-null   str
 2   time                6060 non-null   str
 3   branch_name         6060 non-null   str
 4   district            6060 non-null   str
 5   channel             6060 non-null   str
 6   transaction_type    6060 non-null   str
 7   card_type           3461 non-null   str
 8   account_type        6060 non-null   str
 9   amount_npr          6060 non-null   float64
 10  response_code       6060 non-null   int64
 11  response_message    6060 non-null   str
 12  transaction_status  6060 non-null   str
 13  customer_age        5941 non-null   float64
 14  customer_gender     5968 non-null   str
 15  processing_time_ms  6060 non-null   int64
dtypes: float64(2), int64(2), str(12)
memory usage: 757.6 KB

          amount_npr  response_code  customer_age  processing_time_ms
count    6060.000000    6060.000000   5941.000000         6060.000000
mean     8586.476797       6.142244     34.737755          835.182508
std     20667.251508      19.742012     11.414471          425.068837
min    -20000.000000       0.000000      0.000000           80.000000
25%         0.000000       0.000000     26.000000          524.000000
50%      1000.000000       0.000000     34.000000          754.000000
75%      7306.665000       0.000000     42.000000         1093.000000
max    198498.260000      96.000000    150.000000         2479.000000

In [9]:
print("rows:", df.shape[0], "columns:", df.shape[1])

rows: 6060 columns: 16

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6060 entries, 0 to 6059
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      6060 non-null   str
 1   date                6060 non-null   str
 2   time                6060 non-null   str
 3   branch_name         6060 non-null   str
 4   district            6060 non-null   str
 5   channel             6060 non-null   str
 6   transaction_type    6060 non-null   str
 7   card_type           3461 non-null   str
 8   account_type        6060 non-null   str
 9   amount_npr          6060 non-null   float64
 10  response_code       6060 non-null   int64
 11  response_message    6060 non-null   str
 12  transaction_status  6060 non-null   str
 13  customer_age        5941 non-null   float64
 14  customer_gender     5968 non-null   str
 15  processing_time_ms  6060 non-null   int64
dtypes: float64(2), int64(2), str(12)
memory usage: 757.6 KB

In [11]:
df.describe()

          amount_npr  response_code  customer_age  processing_time_ms
count    6060.000000    6060.000000   5941.000000         6060.000000
mean     8586.476797       6.142244     34.737755          835.182508
std     20667.251508      19.742012     11.414471          425.068837
min    -20000.000000       0.000000      0.000000           80.000000
25%         0.000000       0.000000     26.000000          524.000000
50%      1000.000000       0.000000     34.000000          754.000000
75%      7306.665000       0.000000     42.000000         1093.000000
max    198498.260000      96.000000    150.000000         2479.000000

In [12]:
print(df["branch_name"].head())

0       New Baneshwor
1    Dhangadhi Branch
2      Hetauda Branch
3       Butwal Branch
4     Janakpur Branch
Name: branch_name, dtype: str